name: 'Print version of the action being used'
description: 'This action simply prints the version that has being used to call this action'
outputs:
  version:
    description: "A string printing the version"
    value: ${{ steps.out.outputs.version }}
runs:
  using: "composite"
  steps:
    - id: version
      uses: actions/github-script@v7
      with:
        result-encoding: string
        script: |
          const path = require('node:path'); 
          const {GITHUB_ACTION_PATH} = process.env

          return path.basename(`${GITHUB_ACTION_PATH}`)

    - name: Output folder version
      id: out
      shell: bash
      run: echo 'version=${{ steps.version.outputs.result }}' | tee -a "$GITHUB_OUTPUT"
