name: Run on PR

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  on-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: ver
        uses: ./
      - uses: actions/github-script@v7
        env:
          VERSION: ${{ steps.ver.outputs.version }}
        with:
          script: |
            const {VERSION} = process.env

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${VERSION}`
            })
