name: Run on PR
on:
  pull_request:
jobs:
  on-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: environment
        uses: ./
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '${{ steps.environment.outputs.envs }}'
            })
