name: Run on PR

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  on-pr:
    runs-on: ubuntu-latest
    steps:
      - id: major
        uses: kang-makes/test-action@v1
      - uses: actions/github-script@v7
        env:
          VERSION: ${{ steps.major.outputs.version }}
        with:
          script: |
            const {VERSION} = process.env

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Environment variables for major
                ${VERSION}`
            })

      - id: minor
        uses: kang-makes/test-action@v1.0
      - uses: actions/github-script@v7
        env:
          VERSION: ${{ steps.minor.outputs.version }}
        with:
          script: |
            const {VERSION} = process.env

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Environment variables for minor
                ${VERSION}`
            })

      - id: patch
        uses: kang-makes/test-action@v1.0.1
      - uses: actions/github-script@v7
        env:
          VERSION: ${{ steps.patch.outputs.version }}
        with:
          script: |
            const {VERSION} = process.env

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Environment variables for patch
                ${VERSION}`
            })

      - id: branch
        uses: kang-makes/test-action@main
      - uses: actions/github-script@v7
        env:
          VERSION: ${{ steps.branch.outputs.version }}
        with:
          script: |
            const {VERSION} = process.env

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Environment variables for branch
                ${VERSION}`
            })

      - id: commit
        uses: kang-makes/test-action@f7d1bf9ea65ab389d242030c71cc3790b288d8d9
      - uses: actions/github-script@v7
        env:
          VERSION: ${{ steps.commit.outputs.version }}
        with:
          script: |
            const {VERSION} = process.env

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Environment variables for commit
                ${VERSION}`
            })
